name: Gh-Pages

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: example

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: erickzanardo/flutter-gh-pages@v3
        with:
          webRenderer: canvaskit
          workingDir: example
